name: Release Github Packages

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run.'
        required: true
        default: 'deploy'

jobs:

  build-stable:
    name: Build Stable Image
    if: ${{ github.event.inputs.job == 'deploy'}}
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - run: |
          docker build . -t ghcr.io/${{ github.actor }}/${{ secrets.image }}:stable
          docker push ghcr.io/${{ github.actor }}/${{ secrets.image }}:stable
  build-latest:
    name: Build Latest Image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - run: |
          docker build . -t ghcr.io/${{ github.actor }}/${{ secrets.image }}:latest
          docker push ghcr.io/${{ github.actor }}/${{ secrets.image }}:latest
